### PR TITLE
Added the project list page

### PR DESCRIPTION
**Pull request by ayong8**

### CODE REVIEW

**Comment by ptgolden** [comment]
I'll leave a few comments related to the commit..

**Comment by ptgolden** [comment]
First, in terms of style, is there a reason why you added a component's name as part of its html class name? For example, in https://github.com/editorsnotes/editorsnotes-renderer/pull/34/files#diff-14fa8bf52da6dea7174f7e1b1b00ae7bR63, you define the header as

``` html
<h3 className="ProjectName">
```

instead of just `<h3>`. It won't do any harm to have extra class names, of course, but I've been using basscss classnames exclusively as much as possible. I only add such upper-cased classnames if I need to do some extra-specific styling, for example in https://github.com/editorsnotes/editorsnotes-renderer/blob/07ef685c20900798a68e195c8307abdaab4b9dc2/style/main.css#L50-L76

**Comment by ptgolden** [comment]
I see you've left a place for "trending projects." This is not built into the API and I'm not sure it's a high priority to add such a mechanism right now. I'd imagine we'll mostly sort by projects most recently updated (which is kind of a proxy to "trending", anyway)

**Comment by ptgolden** [comment]
The content is generated with filler data right now, but I see you've added the code to generate it for the API. Can you remove the filler data?

**Comment by ptgolden** [comment]
Also, good job on building another page on top of my Rube Goldberg machine of an application. The issues I pointed out are very minor and I think we'll be able to merge this tomorrow.

**Comment by ayong8** [comment]
- For the className, I added semantic classes for every tag to make more sense of what each tag is for. Since I listed all divs with dummy tags rather than using actual data, adding those classes made me locate each tag I want to work on. I'm fine with deleting those classes to make the code consistent
- About trending topic, what I did on that page was kind of practice to just get familiar with the code, so I don't insist to stick to that layout. I can delete that or just leave it as it is and switch to another better one later.
- I'm not clear about what "filler data" means. Could you explain what it means?

**Comment by ptgolden** [comment]
> For the className, I added semantic classes for every tag to make more sense of what each tag is for. Since I listed all divs with dummy tags rather than using actual data, adding those classes made me locate each tag I want to work on. I'm fine with deleting those classes to make the code consistent

OK, great, that makes sense. Yes, please take them out before we merge this in.

> About trending topic, what I did on that page was kind of practice to just get familiar with the code, so I don't insist to stick to that layout. I can delete that or just leave it as it is and switch to another better one later.

Yes, you'll need to take it out, since we can't populate it with anything (since such a category doesn't exist in the API)

> I'm not clear about what "filler data" means. Could you explain what it means?

I mean that you hard-coded in data (i.e. "The Emma Goldman Papers") instead of generating it purely from the server.

**Comment by ayong8** [comment]
Hi Patrick,
Can you check the commit I just made?
Thanks.

Yongsu

켜짐 February 25, 2016 에서 1:06:19 PM, Patrick Golden (notifications@github.com) 작성됨:

For the className, I added semantic classes for every tag to make more sense of what each tag is for. Since I listed all divs with dummy tags rather than using actual data, adding those classes made me locate each tag I want to work on. I'm fine with deleting those classes to make the code consistent

OK, great, that makes sense. Yes, please take them out before we merge this in.

About trending topic, what I did on that page was kind of practice to just get familiar with the code, so I don't insist to stick to that layout. I can delete that or just leave it as it is and switch to another better one later.

Yes, you'll need to take it out, since we can't populate it with anything (since such a category doesn't exist in the API)

I'm not clear about what "filler data" means. Could you explain what it means?

I mean that you hard-coded in data (i.e. "The Emma Goldman Papers") instead of generating it purely from the server.

**Comment by ptgolden** [comment]
Good work, Yongsu. I fixed a couple bugs and made the coding style similar to other components.

**Pull request merged**
